# Do not edit by hand — generated by generate-nix-options from the server's
# Clap definition and the `--config` loader's section tables. Regenerate with:
#
#   cargo run --bin generate-nix-options > nix/options.nix
#
# CI's docs-generated-check regenerates and diffs this file, so it cannot
# drift from the binary. Each option maps 1:1 to a config-file key (see
# site-docs/reference/config-file.md); `null` (the default everywhere) omits
# the key from the generated config file, so the server's built-in default
# and any MCP_V8_* environment variable apply unchanged.
{ lib }:
{
  advertise_addr = lib.mkOption {
    type = lib.types.nullOr lib.types.str;
    default = null;
    description = "Advertise address for this node (host:port). Used for peer discovery and write forwarding. Defaults to <node-id>:<cluster-port>. Config-file key for the `--advertise-addr` flag. Environment variable: `MCP_V8_ADVERTISE_ADDR`.";
  };
  allow_external_modules = lib.mkOption {
    type = lib.types.nullOr lib.types.bool;
    default = null;
    description = "Allow external module imports (npm:, jsr:, and URL imports). When disabled (the default), code using import declarations for external packages will be rejected. Enable with --allow-external-modules. Config-file key for the `--allow-external-modules` flag. Environment variable: `MCP_V8_ALLOW_EXTERNAL_MODULES`. Server default: `false`.";
  };
  allow_run_js_file = lib.mkOption {
    type = lib.types.nullOr lib.types.bool;
    default = null;
    description = "Allow the `run_js` tool to read its code from a file on the server's own filesystem (the `file` parameter). OFF by default. When set, ANY path the server process can read is allowed — this is the easy \"allow all\" switch. For finer control, leave this off and configure a `run_js_file` policy in --policies-json instead (a Rego/OPA chain decides which paths are allowed); the policy input is `{ \"operation\": \"read\", \"path\": \"<canonical path>\" }`. This flag takes precedence over a configured run_js_file policy. Config-file key for the `--allow-run-js-file` flag. Environment variable: `MCP_V8_ALLOW_RUN_JS_FILE`. Server default: `false`.";
  };
  bind_host = lib.mkOption {
    type = lib.types.nullOr lib.types.str;
    default = null;
    description = "Host/address the HTTP and SSE transports bind to. Defaults to all IPv4 interfaces (0.0.0.0). Set to \"::\" for a dual-stack IPv6 listener, which is required to be reachable over IPv6-resolving private networks (e.g. Railway). Config-file key for the `--bind-host` flag. Environment variable: `MCP_V8_BIND_HOST`. Server default: `0.0.0.0`.";
  };
  cache_dir = lib.mkOption {
    type = lib.types.nullOr lib.types.str;
    default = null;
    description = "Local filesystem cache directory for S3 write-through caching (only used with `--s3-bucket`). Config-file key for the `--cache-dir` flag. Environment variable: `MCP_V8_CACHE_DIR`.";
  };
  cluster_port = lib.mkOption {
    type = lib.types.nullOr lib.types.port;
    default = null;
    description = "Port for the Raft cluster HTTP server. Enables cluster mode when set. Config-file key for the `--cluster-port` flag. Environment variable: `MCP_V8_CLUSTER_PORT`.";
  };
  election_timeout_max = lib.mkOption {
    type = lib.types.nullOr lib.types.ints.unsigned;
    default = null;
    description = "Maximum election timeout in milliseconds. Config-file key for the `--election-timeout-max` flag. Environment variable: `MCP_V8_ELECTION_TIMEOUT_MAX`. Server default: `500`.";
  };
  election_timeout_min = lib.mkOption {
    type = lib.types.nullOr lib.types.ints.unsigned;
    default = null;
    description = "Minimum election timeout in milliseconds. Config-file key for the `--election-timeout-min` flag. Environment variable: `MCP_V8_ELECTION_TIMEOUT_MIN`. Server default: `300`.";
  };
  execution_timeout = lib.mkOption {
    type = lib.types.nullOr lib.types.ints.unsigned;
    default = null;
    description = "Maximum execution timeout in seconds (default: 30, max: 300). Config-file key for the `--execution-timeout` flag. Environment variable: `MCP_V8_EXECUTION_TIMEOUT`. Server default: `30`.";
  };
  fetch_header_config = lib.mkOption {
    type = lib.types.nullOr lib.types.str;
    default = null;
    description = "JSON array of header injection rules (a path to a JSON file, or inline JSON — also settable as the `fetch_headers` section of a --config file). Each rule sets \"host\" (plus optional \"methods\") and exactly one of \"headers\" or \"auth\". Static: [{\"host\": \"api.github.com\", \"methods\": [\"GET\",\"POST\"], \"headers\": {\"Authorization\": \"Bearer ...\"}}] OAuth: [{\"host\": \"api.example.com\", \"auth\": {\"type\": \"oauth_client_credentials\", \"header\": \"Authorization\", \"token_url\": \"https://issuer.example.com/token\", \"client_id\": \"abc\", \"client_secret\": \"xyz\", \"scope\": \"read:all\", \"refresh_buffer_secs\": 30}}]. Config-file key for the `--fetch-header-config` flag. Environment variable: `MCP_V8_FETCH_HEADER_CONFIG`.";
  };
  fetch_headers = lib.mkOption {
    type = lib.types.nullOr (lib.types.listOf (lib.types.attrsOf lib.types.anything));
    default = null;
    description = "Structured `fetch_headers` section of the config file; the inline equivalent of the `--fetch-header-config` flag (and mutually exclusive with the `fetch_header_config` key). JSON array of header injection rules (a path to a JSON file, or inline JSON — also settable as the `fetch_headers` section of a --config file). Each rule sets \"host\" (plus optional \"methods\") and exactly one of \"headers\" or \"auth\". Static: [{\"host\": \"api.github.com\", \"methods\": [\"GET\",\"POST\"], \"headers\": {\"Authorization\": \"Bearer ...\"}}] OAuth: [{\"host\": \"api.example.com\", \"auth\": {\"type\": \"oauth_client_credentials\", \"header\": \"Authorization\", \"token_url\": \"https://issuer.example.com/token\", \"client_id\": \"abc\", \"client_secret\": \"xyz\", \"scope\": \"read:all\", \"refresh_buffer_secs\": 30}}].";
  };
  fs_dir = lib.mkOption {
    type = lib.types.nullOr lib.types.str;
    default = null;
    description = "Directory for the fs snapshot blob store (chunks + manifests) when `--fs-store dir`. Defaults to `<session-db-path>/fs-blobs`. Config-file key for the `--fs-dir` flag. Environment variable: `MCP_V8_FS_DIR`.";
  };
  fs_labels_db = lib.mkOption {
    type = lib.types.nullOr lib.types.str;
    default = null;
    description = "Path for the fs label/reflog database (sled). Defaults to `<session-db-path>/fs-labels`. Config-file key for the `--fs-labels-db` flag. Environment variable: `MCP_V8_FS_LABELS_DB`.";
  };
  fs_passthrough = lib.mkOption {
    type = lib.types.nullOr lib.types.bool;
    default = null;
    description = "Overlay read behaviour when a per-session fs snapshot is mounted. Off (default): overlay-only — the mounted snapshot is the entire fs view, so a read that misses it is ENOENT (strict isolation). On: overlayfs-style — fall through to the real filesystem as a read-only lower layer (still gated by the filesystem policy), so bundled read-only paths like `/opt/languages` resolve while `/work` stays the per-session overlay. Config-file key for the `--fs-passthrough` flag. Environment variable: `MCP_V8_FS_PASSTHROUGH`. Server default: `false`.";
  };
  fs_store = lib.mkOption {
    type = lib.types.nullOr (lib.types.enum [ "none" "dir" "s3" ]);
    default = null;
    description = "Content-addressed `/work` filesystem backend. `none` (default) = no fs persistence. `dir` = node-local blob store (`--fs-dir`). `s3` = shared `--s3-bucket`. When enabled, the `fs` parameter of run_js can mount a snapshot (by label or CA id) and the `fs_*` tools / `/api/fs/...` endpoints become functional. Works with any isolate (compatible with `--wasm-module`). In cluster mode labels replicate cluster-wide, but blobs/manifests are only shared when stored on shared storage — so `--fs-store s3` is required when running fs persistence in a cluster. Config-file key for the `--fs-store` flag. Environment variable: `MCP_V8_FS_STORE`. Server default: `none`.";
  };
  harden_freeze_ops = lib.mkOption {
    type = lib.types.nullOr lib.types.bool;
    default = null;
    description = "Freeze `Deno.core.ops` so user code cannot replace/intercept any op (e.g. a persistent trojan op surviving in stateful/snapshot mode). Config-file key for the `--harden-freeze-ops` flag. Environment variable: `MCP_V8_HARDEN_FREEZE_OPS`. Server default: `false`.";
  };
  harden_neutralize_introspection = lib.mkOption {
    type = lib.types.nullOr lib.types.bool;
    default = null;
    description = "Neutralize `op_memory_usage` + `op_is_terminal` (host info leaks). Config-file key for the `--harden-neutralize-introspection` flag. Environment variable: `MCP_V8_HARDEN_NEUTRALIZE_INTROSPECTION`. Server default: `false`.";
  };
  harden_neutralize_proxy_details = lib.mkOption {
    type = lib.types.nullOr lib.types.bool;
    default = null;
    description = "Neutralize `op_get_proxy_details` (otherwise it bypasses `Proxy` handlers and can read a proxied target). Config-file key for the `--harden-neutralize-proxy-details` flag. Environment variable: `MCP_V8_HARDEN_NEUTRALIZE_PROXY_DETAILS`. Server default: `false`.";
  };
  harden_remove_bootstrap = lib.mkOption {
    type = lib.types.nullOr lib.types.bool;
    default = null;
    description = "Remove `globalThis.__bootstrap` (event-loop hooks, primordials such as a pristine `Function` constructor, and internal registries). Config-file key for the `--harden-remove-bootstrap` flag. Environment variable: `MCP_V8_HARDEN_REMOVE_BOOTSTRAP`. Server default: `false`.";
  };
  harden_remove_shared_memory = lib.mkOption {
    type = lib.types.nullOr lib.types.bool;
    default = null;
    description = "Remove `globalThis.SharedArrayBuffer` + `globalThis.Atomics` — the high-resolution Spectre-timer prerequisite. NOTE: these are also the shared-memory primitives emscripten wasm-threads require, so leave this OFF to run pthreads-based WASM modules. Config-file key for the `--harden-remove-shared-memory` flag. Environment variable: `MCP_V8_HARDEN_REMOVE_SHARED_MEMORY`. Server default: `false`.";
  };
  heap_dir = lib.mkOption {
    type = lib.types.nullOr lib.types.str;
    default = null;
    description = "Directory for the heap-snapshot store when `--heap-store dir`. Defaults to /tmp/mcp-v8-heaps. Config-file key for the `--heap-dir` flag. Environment variable: `MCP_V8_HEAP_DIR`.";
  };
  heap_memory_max = lib.mkOption {
    type = lib.types.nullOr lib.types.ints.unsigned;
    default = null;
    description = "Maximum V8 heap memory per isolate in megabytes (default: 8). Config-file key for the `--heap-memory-max` flag. Environment variable: `MCP_V8_HEAP_MEMORY_MAX`. Server default: `8`.";
  };
  heap_store = lib.mkOption {
    type = lib.types.nullOr (lib.types.enum [ "none" "dir" "s3" ]);
    default = null;
    description = "V8 heap-snapshot backend. `none` (default) = no heap persistence; JS globals do NOT survive between runs. `dir` = node-local directory (`--heap-dir`). `s3` = shared `--s3-bucket` (optionally `--cache-dir`). Heap snapshots require a V8 SnapshotCreator isolate, which disables WebAssembly — so heap persistence is mutually exclusive with `--wasm-module`/`--wasm-config` (rejected at startup). Config-file key for the `--heap-store` flag. Environment variable: `MCP_V8_HEAP_STORE`. Server default: `none`.";
  };
  heartbeat_interval = lib.mkOption {
    type = lib.types.nullOr lib.types.ints.unsigned;
    default = null;
    description = "Heartbeat interval in milliseconds. Config-file key for the `--heartbeat-interval` flag. Environment variable: `MCP_V8_HEARTBEAT_INTERVAL`. Server default: `100`.";
  };
  http_port = lib.mkOption {
    type = lib.types.nullOr lib.types.port;
    default = null;
    description = "HTTP port using Streamable HTTP transport (MCP 2025-03-26+, load-balanceable). Config-file key for the `--http-port` flag. Environment variable: `MCP_V8_HTTP_PORT`.";
  };
  instructions = lib.mkOption {
    type = lib.types.nullOr lib.types.str;
    default = null;
    description = "Override the MCP server `instructions` (the \"system prompt\" the server reports to clients during `initialize`). The value is used verbatim as inline text, unless it begins with `@`, in which case the remainder is treated as a path to a file whose contents are used (`@-` is not special; use `@@` for a literal leading `@`). Examples: --instructions \"Run JS for me\" --instructions @./prompt.txt. Config-file key for the `--instructions` flag. Environment variable: `MCP_V8_INSTRUCTIONS`.";
  };
  join = lib.mkOption {
    type = lib.types.nullOr lib.types.str;
    default = null;
    description = "Join an existing cluster by contacting this seed address (host:port). The node will register itself with the cluster leader via /raft/join. Config-file key for the `--join` flag. Environment variable: `MCP_V8_JOIN`.";
  };
  join_as_learner = lib.mkOption {
    type = lib.types.nullOr lib.types.bool;
    default = null;
    description = "Join as a non-voting learner: the node replicates the log but is excluded from election and commit quorums and never starts elections. Use for ephemeral nodes whose churn must not affect availability. Config-file key for the `--join-as-learner` flag. Environment variable: `MCP_V8_JOIN_AS_LEARNER`.";
  };
  jwks_url = lib.mkOption {
    type = lib.types.nullOr lib.types.str;
    default = null;
    description = "JWKS endpoint URL for fetching public keys (e.g., Keycloak OIDC certs URL). Enables JWT verification of Authorization: Bearer tokens during initialize. Config-file key for the `--jwks-url` flag. Environment variable: `JWKS_URL`.";
  };
  max_concurrent_executions = lib.mkOption {
    type = lib.types.nullOr lib.types.ints.unsigned;
    default = null;
    description = "Maximum concurrent V8 executions (default: CPU core count). Config-file key for the `--max-concurrent-executions` flag. Environment variable: `MCP_V8_MAX_CONCURRENT_EXECUTIONS`.";
  };
  mcp_config = lib.mkOption {
    type = lib.types.nullOr lib.types.str;
    default = null;
    description = "JSON config for MCP server modules (a path to a JSON file, or inline JSON — also settable as the `mcp_servers` section of a --config file). Format: [{\"name\": \"srv\", \"transport\": \"stdio\", \"command\": \"cmd\", \"args\": [\"a\"]}, {\"name\": \"srv2\", \"transport\": \"sse\", \"url\": \"http://...\"}]. Config-file key for the `--mcp-config` flag. Environment variable: `MCP_V8_MCP_CONFIG`.";
  };
  mcp_servers = lib.mkOption {
    type = lib.types.nullOr (lib.types.listOf (lib.types.attrsOf lib.types.anything));
    default = null;
    description = "Structured `mcp_servers` section of the config file; the inline equivalent of the `--mcp-config` flag (and mutually exclusive with the `mcp_config` key). JSON config for MCP server modules (a path to a JSON file, or inline JSON — also settable as the `mcp_servers` section of a --config file). Format: [{\"name\": \"srv\", \"transport\": \"stdio\", \"command\": \"cmd\", \"args\": [\"a\"]}, {\"name\": \"srv2\", \"transport\": \"sse\", \"url\": \"http://...\"}].";
  };
  mcp_stub_prefix = lib.mkOption {
    type = lib.types.nullOr lib.types.str;
    default = null;
    description = "Prefix applied to stub tool names. Defaults to `runjs__` so it is obvious to a calling agent that these tools execute through the JS runtime rather than dispatching directly. Has no effect when --mcp-stubs is false. Config-file key for the `--mcp-stub-prefix` flag. Environment variable: `MCP_V8_MCP_STUB_PREFIX`. Server default: `runjs__`.";
  };
  mcp_stubs = lib.mkOption {
    type = lib.types.nullOr lib.types.bool;
    default = null;
    description = "Expose upstream MCP server tools on the MCPJS server itself as `<prefix><server>__<tool>` stubs. When `true` (the default whenever at least one --mcp-server is configured), an external client of MCPJS can discover those tools via tools/list and tool search; calling a stub returns instructional text telling the caller to invoke the tool from JavaScript via run_js + mcp.callTool(...). Pass `--mcp-stubs false` to disable. Config-file key for the `--mcp-stubs` flag. Environment variable: `MCP_V8_MCP_STUBS`. Server default: `true`.";
  };
  metadata_only = lib.mkOption {
    type = lib.types.nullOr lib.types.bool;
    default = null;
    description = "Run as a metadata-only cluster node: serve Raft replication of session metadata (session log, heap tags, fs labels) and nothing else. No V8 engine is created, no MCP transport or REST sidecar is started, and no policies are needed — the node's only surface is the Raft HTTP server on --cluster-port, where it acts purely as a leader or replica for the replicated metadata store. Requires --cluster-port and conflicts with the MCP transports and all JS-execution configuration. Config-file key for the `--metadata-only` flag. Environment variable: `MCP_V8_METADATA_ONLY`. Server default: `false`.";
  };
  node_id = lib.mkOption {
    type = lib.types.nullOr lib.types.str;
    default = null;
    description = "Unique node identifier within the cluster. Config-file key for the `--node-id` flag. Environment variable: `MCP_V8_NODE_ID`. Server default: `node1`.";
  };
  peers = lib.mkOption {
    type = lib.types.nullOr (lib.types.listOf lib.types.str);
    default = null;
    description = "Comma-separated list of seed peer addresses. Peers can also join dynamically via POST /raft/join. Forms: id@host:port — peer address with an explicit node id host:port — peer address only (node id learned on join) Examples: node2@10.0.0.2:4000 10.0.0.3:4000. Config-file key for the `--peers` flag. Environment variable: `MCP_V8_PEERS`.";
  };
  policies = lib.mkOption {
    type = lib.types.nullOr (lib.types.attrsOf lib.types.anything);
    default = null;
    description = "Structured `policies` section of the config file; the inline equivalent of the `--policies-json` flag (and mutually exclusive with the `policies_json` key). JSON policy configuration (inline JSON or path to a JSON file). Enables fetch() and/or module policy gating via local Rego files and/or remote OPA servers. Example: --policies-json '{\"fetch\":{\"policies\":[{\"url\":\"file:///path/to/fetch.rego\"}]}}' Schema: { \"fetch\": { \"mode\": \"all\"|\"any\", \"policies\": [{\"url\": \"...\", \"policy_path\": \"...\", \"rule\": \"...\"}] }, \"modules\": { ... } }.";
  };
  policies_json = lib.mkOption {
    type = lib.types.nullOr lib.types.str;
    default = null;
    description = "JSON policy configuration (inline JSON or path to a JSON file). Enables fetch() and/or module policy gating via local Rego files and/or remote OPA servers. Example: --policies-json '{\"fetch\":{\"policies\":[{\"url\":\"file:///path/to/fetch.rego\"}]}}' Schema: { \"fetch\": { \"mode\": \"all\"|\"any\", \"policies\": [{\"url\": \"...\", \"policy_path\": \"...\", \"rule\": \"...\"}] }, \"modules\": { ... } }. Config-file key for the `--policies-json` flag. Environment variable: `MCP_V8_POLICIES_JSON`.";
  };
  run_js_description = lib.mkOption {
    type = lib.types.nullOr lib.types.str;
    default = null;
    description = "Override the description advertised for the `run_js` tool in `tools/list`. The value is used verbatim as inline text, unless it begins with `@`, in which case the remainder is treated as a path to a file whose contents are used (use `@@` for a literal leading `@`). Examples: --run-js-description \"Execute JS\" --run-js-description @./run_js.md. Config-file key for the `--run-js-description` flag. Environment variable: `MCP_V8_RUN_JS_DESCRIPTION`.";
  };
  s3_bucket = lib.mkOption {
    type = lib.types.nullOr lib.types.str;
    default = null;
    description = "S3 bucket backing whichever axes select `s3`. Required when `--heap-store s3` or `--fs-store s3` is set. Config-file key for the `--s3-bucket` flag. Environment variable: `MCP_V8_S3_BUCKET`.";
  };
  sandbox_manifest = lib.mkOption {
    type = lib.types.nullOr lib.types.str;
    default = null;
    description = "Confine the whole server process with an OS-enforced sandbox (nono: Landlock on Linux 5.13+, Seatbelt on macOS) described by a nono capability manifest JSON file. nono capabilities compose additively, so the enforced set is the manifest (verbatim, in nono's schema and semantics) unioned with a server baseline derived from this configuration: storage directories read-write, config/policy/WASM inputs and system paths read-only, and bind grants for configured listener ports. The manifest owns the network egress posture — the baseline never opens outbound access. Applied before the async runtime and V8 spawn any threads; irreversible once applied. This is defense in depth *underneath* the OPA policy layer. Fails closed: startup aborts if the platform cannot enforce the composed set, and manifest features that need nono's CLI supervisor (network proxy mode, credentials, rollback, fs deny rules) are rejected rather than silently ignored. Config-file key for the `--sandbox-manifest` flag. Environment variable: `MCP_V8_SANDBOX_MANIFEST`.";
  };
  session_db_path = lib.mkOption {
    type = lib.types.nullOr lib.types.str;
    default = null;
    description = "Path to the sled database for the session log (per-session heap+fs history) and the execution registry. Also the default parent for the heap-tag store, fs blob store, and fs label db. Default: /tmp/mcp-v8-sessions. Config-file key for the `--session-db-path` flag. Environment variable: `MCP_V8_SESSION_DB_PATH`. Server default: `/tmp/mcp-v8-sessions`.";
  };
  session_fork_from = lib.mkOption {
    type = lib.types.nullOr lib.types.str;
    default = null;
    description = "Fork the new session (given by --session-id) from a previous session's latest heap+fs snapshot. The new session starts with the source session's state but is independent: subsequent snapshots are written under the new session id, leaving the source untouched (copy-on-write). Requires --session-id and heap and/or fs persistence. No-op if the target session already has history. Config-file key for the `--session-fork-from` flag. Environment variable: `MCP_V8_SESSION_FORK_FROM`.";
  };
  session_id = lib.mkOption {
    type = lib.types.nullOr lib.types.str;
    default = null;
    description = "Fixed session id for this process, used when no X-MCP-Session-Id header is available (i.e. the stdio transport). Keys per-session heap+fs state so a process spawned for a given logical session (e.g. one per thread) resumes that session's stateful heap+fs. Over HTTP the header still wins. Config-file key for the `--session-id` flag. Environment variable: `MCP_V8_SESSION_ID`.";
  };
  sse_port = lib.mkOption {
    type = lib.types.nullOr lib.types.port;
    default = null;
    description = "SSE port using the legacy HTTP+SSE transport (served by a vendored rmcp 0.1.5; no MCP tasks support — use --http-port for tasks). Config-file key for the `--sse-port` flag. Environment variable: `MCP_V8_SSE_PORT`.";
  };
  wasm = lib.mkOption {
    type = lib.types.nullOr (lib.types.attrsOf lib.types.anything);
    default = null;
    description = "Structured `wasm` section of the config file; the inline equivalent of the `--wasm-config` flag (and mutually exclusive with the `wasm_config` key). JSON config mapping global names to .wasm file paths or objects (a path to a JSON file, or inline JSON — also settable as the `wasm` section of a --config file). String value: {\"name\": \"/path/to/module.wasm\"} Object value: {\"name\": {\"path\": \"/path/to/module.wasm\", \"max_memory_bytes\": 16777216, \"description\": \"what the module does\"}} The optional \"description\" sets the MCP stub tool's description. NOTE: incompatible with heap persistence (`--heap-store` other than none).";
  };
  wasm_config = lib.mkOption {
    type = lib.types.nullOr lib.types.str;
    default = null;
    description = "JSON config mapping global names to .wasm file paths or objects (a path to a JSON file, or inline JSON — also settable as the `wasm` section of a --config file). String value: {\"name\": \"/path/to/module.wasm\"} Object value: {\"name\": {\"path\": \"/path/to/module.wasm\", \"max_memory_bytes\": 16777216, \"description\": \"what the module does\"}} The optional \"description\" sets the MCP stub tool's description. NOTE: incompatible with heap persistence (`--heap-store` other than none). Config-file key for the `--wasm-config` flag. Environment variable: `MCP_V8_WASM_CONFIG`.";
  };
  wasm_default_max_memory = lib.mkOption {
    type = lib.types.nullOr lib.types.str;
    default = null;
    description = "Default max native memory for WASM modules without a per-module limit. Supports suffixes: k/K (KiB), m/M (MiB), g/G (GiB), or raw bytes. This is separate from --heap-memory-max (JS heap); WASM linear memory is allocated as native memory outside the V8 heap. Config-file key for the `--wasm-default-max-memory` flag. Environment variable: `MCP_V8_WASM_DEFAULT_MAX_MEMORY`. Server default: `16m`.";
  };
  wasm_stub_prefix = lib.mkOption {
    type = lib.types.nullOr lib.types.str;
    default = null;
    description = "Prefix applied to WASM stub tool names. Defaults to `runjs__` so it is obvious to a calling agent that these modules execute through the JS runtime rather than dispatching directly. Has no effect when --wasm-stubs is false. Config-file key for the `--wasm-stub-prefix` flag. Environment variable: `MCP_V8_WASM_STUB_PREFIX`. Server default: `runjs__`.";
  };
  wasm_stubs = lib.mkOption {
    type = lib.types.nullOr lib.types.bool;
    default = null;
    description = "Expose pre-loaded WASM modules on the MCPJS server itself as `<prefix>wasm__<name>` stubs. When `true` (the default whenever at least one WASM module is loaded), an external client of MCPJS can discover the module via tools/list and tool search; calling a stub returns instructional text telling the caller to use the module from JavaScript via run_js (the module is available as the `__wasm_<name>` global). Pass `--wasm-stubs false` to disable. Config-file key for the `--wasm-stubs` flag. Environment variable: `MCP_V8_WASM_STUBS`. Server default: `true`.";
  };
}
