[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
mcpr = "0.2.3"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = "1.44.2"
v8 = "136.0.0"
