version: "3.8"









services:
  
  lb:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx-cluster.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node1
      - node2
      - node3

  
  node1:
    build: .
    command:
      - --http-port=3000
      - --cluster-port=4000
      - --node-id=node1
      - --peers=node2@node2:4000,node3@node3:4000
      - --heartbeat-interval=200
      - --election-timeout-min=1000
      - --election-timeout-max=2000
    expose:
      - "3000"
      - "4000"

  node2:
    build: .
    command:
      - --http-port=3000
      - --cluster-port=4000
      - --node-id=node2
      - --peers=node1@node1:4000,node3@node3:4000
      - --heartbeat-interval=200
      - --election-timeout-min=1000
      - --election-timeout-max=2000
    expose:
      - "3000"
      - "4000"

  node3:
    build: .
    command:
      - --http-port=3000
      - --cluster-port=4000
      - --node-id=node3
      - --peers=node1@node1:4000,node2@node2:4000
      - --heartbeat-interval=200
      - --election-timeout-min=1000
      - --election-timeout-max=2000
    expose:
      - "3000"
      - "4000"
