version: "3.8"









services:
  
  lb:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx-single.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node1

  
  node1:
    build: .
    command:
      - --http-port=3000
      - --heap-store=dir
      - --heap-dir=/data/heaps
      - --session-db-path=/data/sessions
    volumes:
      - node1-data:/data
    expose:
      - "3000"

volumes:
  node1-data:
