/* tslint:disable */
/* eslint-disable */
/**
 * webserver
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { JavaScriptInput } from '../models';
import { JavaScriptOutput } from '../models';
import { LogInput } from '../models';
import { LogOutput } from '../models';
/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Evaluate JavaScript code  Evaluates the provided JavaScript code and returns the result.
         * @param {JavaScriptInput} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        handlersJavascriptJavascript: async (body: JavaScriptInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling handlersJavascriptJavascript.');
            }
            const localVarPath = `/javascript`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get instance ID from queue  Retrieves the next available EC2 instance ID from the queue.
         * @param {LogInput} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        handlersLogLog: async (body: LogInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling handlersLogLog.');
            }
            const localVarPath = `/log`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Evaluate JavaScript code  Evaluates the provided JavaScript code and returns the result.
         * @param {JavaScriptInput} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async handlersJavascriptJavascript(body: JavaScriptInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<JavaScriptOutput>>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).handlersJavascriptJavascript(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get instance ID from queue  Retrieves the next available EC2 instance ID from the queue.
         * @param {LogInput} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async handlersLogLog(body: LogInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<LogOutput>>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).handlersLogLog(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Evaluate JavaScript code  Evaluates the provided JavaScript code and returns the result.
         * @param {JavaScriptInput} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async handlersJavascriptJavascript(body: JavaScriptInput, options?: AxiosRequestConfig): Promise<AxiosResponse<JavaScriptOutput>> {
            return DefaultApiFp(configuration).handlersJavascriptJavascript(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Get instance ID from queue  Retrieves the next available EC2 instance ID from the queue.
         * @param {LogInput} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async handlersLogLog(body: LogInput, options?: AxiosRequestConfig): Promise<AxiosResponse<LogOutput>> {
            return DefaultApiFp(configuration).handlersLogLog(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * Evaluate JavaScript code  Evaluates the provided JavaScript code and returns the result.
     * @param {JavaScriptInput} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public async handlersJavascriptJavascript(body: JavaScriptInput, options?: AxiosRequestConfig) : Promise<AxiosResponse<JavaScriptOutput>> {
        return DefaultApiFp(this.configuration).handlersJavascriptJavascript(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get instance ID from queue  Retrieves the next available EC2 instance ID from the queue.
     * @param {LogInput} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public async handlersLogLog(body: LogInput, options?: AxiosRequestConfig) : Promise<AxiosResponse<LogOutput>> {
        return DefaultApiFp(this.configuration).handlersLogLog(body, options).then((request) => request(this.axios, this.basePath));
    }
}
