//! Derive macro that generates a registry mapping clap argument ids to their
//! "structured grammar" descriptors, replacing a hand-maintained central
//! `structured_args()` Vec.
//!
//! Usage on a clap `#[derive(Parser)]` struct:
//!
//! ```ignore
//! #[derive(Parser, StructuredArgs)]
//! struct Cli {
//!     #[arg(long = "fetch-header")]
//!     #[structured(grammar = crate::cli::fetch_header_grammar)]
//!     pub fetch_headers: Vec<String>,
//! }
//! ```
//!
//! The derive emits:
//!
//! ```ignore
//! impl Cli {
//!     pub fn structured_args() -> Vec<(&'static str, crate::cli::Grammar)> {
//!         vec![("fetch_headers", crate::cli::fetch_header_grammar())]
//!     }
//!     pub fn structured_arg_ids() -> Vec<&'static str> {
//!         vec!["fetch_headers"]
//!     }
//! }
//! ```
//!
//! The string id is the field name, which is the clap argument id clap derives
//! for a field (clap ids are the raw field identifiers, independent of any
//! `long = "..."` rename), so it can be passed straight to
//! `clap::Command::mut_arg`.

use proc_macro::TokenStream;
use quote::quote;
use syn::{parse_macro_input, Data, DeriveInput, Fields, Path};

/// Derive `StructuredArgs`, generating `structured_args()` / `structured_arg_ids()`
/// associated functions from fields annotated with `#[structured(grammar = ...)]`.
#[proc_macro_derive(StructuredArgs, attributes(structured))]
pub fn derive_structured_args(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    match expand(input) {
        Ok(tokens) => tokens.into(),
        Err(err) => err.to_compile_error().into(),
    }
}

fn expand(input: DeriveInput) -> syn::Result<proc_macro2::TokenStream> {
    let struct_name = &input.ident;
    let (impl_generics, ty_generics, where_clause) = input.generics.split_for_impl();

    let fields = match &input.data {
        Data::Struct(data) => match &data.fields {
            Fields::Named(named) => &named.named,
            _ => {
                return Err(syn::Error::new_spanned(
                    struct_name,
                    "StructuredArgs can only be derived for structs with named fields",
                ))
            }
        },
        _ => {
            return Err(syn::Error::new_spanned(
                struct_name,
                "StructuredArgs can only be derived for structs",
            ))
        }
    };

    let mut ids = Vec::new();
    let mut entries = Vec::new();

    for field in fields {
        let Some(grammar_path) = parse_structured_attr(field)? else {
            continue;
        };
        // clap derives the argument id from the raw field identifier.
        let ident = field
            .ident
            .as_ref()
            .expect("named fields always have an identifier");
        let id = ident.to_string();
        ids.push(quote! { #id });
        entries.push(quote! { (#id, #grammar_path()) });
    }

    Ok(quote! {
        impl #impl_generics #struct_name #ty_generics #where_clause {
            /// Argument id -> grammar descriptor for every field annotated with
            /// `#[structured(grammar = ...)]`. Generated by `#[derive(StructuredArgs)]`.
            pub fn structured_args() -> ::std::vec::Vec<(&'static str, Grammar)> {
                ::std::vec![ #(#entries),* ]
            }

            /// The clap argument ids of every structured field, in declaration order.
            pub fn structured_arg_ids() -> ::std::vec::Vec<&'static str> {
                ::std::vec![ #(#ids),* ]
            }
        }
    })
}

/// Parse `#[structured(grammar = path::to::fn)]` from a field, returning the
/// grammar function path if present. Returns `Ok(None)` for fields without the
/// attribute, and an error for malformed attributes.
fn parse_structured_attr(field: &syn::Field) -> syn::Result<Option<Path>> {
    let mut grammar: Option<Path> = None;

    for attr in &field.attrs {
        if !attr.path().is_ident("structured") {
            continue;
        }
        attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("grammar") {
                let value = meta.value()?;
                grammar = Some(value.parse::<Path>()?);
                Ok(())
            } else {
                Err(meta.error("unknown `structured` attribute key; expected `grammar`"))
            }
        })?;
    }

    if grammar.is_none() {
        // Attribute present but no grammar key, or no attribute at all.
        for attr in &field.attrs {
            if attr.path().is_ident("structured") {
                return Err(syn::Error::new_spanned(
                    attr,
                    "`#[structured(...)]` requires a `grammar = path::to::fn` key",
                ));
            }
        }
    }

    Ok(grammar)
}
