#!/usr/bin/env python3
"""Generate Node compatibility JSON and Markdown reports."""

from __future__ import annotations

import argparse
import collections
import json
import pathlib
import sys

from node_compat_common import load_versions

REPO = pathlib.Path(__file__).resolve().parents[2]
DEFAULT_EXPECTATIONS = REPO / "server/tests/node_compat/expectations.json"
DEFAULT_INVENTORY = REPO / "server/tests/node_compat/inventory.json"
DEFAULT_VERSIONS = REPO / "server/tests/node_compat/versions.json"
DEFAULT_JSON = REPO / "server/tests/node_compat/report.json"
DEFAULT_MARKDOWN = REPO / "site-docs/reference/node-compatibility-status.md"
RUNNABLE = {"pass", "fail"}


def counts(values):
    return dict(sorted(collections.Counter(values).items()))


def build_report(expectations, inventory, versions):
    fast = list(expectations.values())
    corpus = inventory["tests"]
    return {
        "schema_version": 1,
        "versions": {
            "fast_suite_node": versions["node"]["tag"],
            "deno_corpus_node": versions["deno_node_test"]["node_version"],
            "deno_node_test_commit": versions["deno_node_test"]["commit"],
            "citgm_commit": versions["citgm"]["commit"],
        },
        "fast_suite": {
            "total": len(fast),
            "runnable": sum(item["status"] in RUNNABLE for item in fast),
            "status": counts(item["status"] for item in fast),
            "family": counts(item["family"] for item in fast),
            "profile": counts(item["profile"] for item in fast),
            "compatibility": counts(item["compatibility"] for item in fast),
        },
        "full_corpus": {
            "total": len(corpus),
            "status": counts(item["status"] for item in corpus),
            "family": counts(item["family"] for item in corpus),
            "profile": counts(item["profile"] for item in corpus),
            "compatibility": counts(item["compatibility"] for item in corpus),
        },
    }


def markdown_table(mapping):
    rows = ["| Name | Count |", "|---|---:|"]
    rows.extend(f"| `{name}` | {count} |" for name, count in mapping.items())
    return rows


def render_markdown(report):
    versions = report["versions"]
    fast = report["fast_suite"]
    corpus = report["full_corpus"]
    lines = [
        "# Node Compatibility Status",
        "",
        "This report is generated by `tools/compat/gen-node-compat-report.py`.",
        "The executable fast suite and the broad inventory use different Node",
        "versions and are intentionally reported separately.",
        "",
        "## Version Pins",
        "",
        f"- Fast executable suite: Node `{versions['fast_suite_node']}`.",
        f"- Deno-vendored inventory corpus: Node `{versions['deno_corpus_node']}` at",
        f"  `denoland/node_test` commit `{versions['deno_node_test_commit']}`.",
        f"- CITGM candidate manifest: commit `{versions['citgm_commit']}`.",
        "",
        "## Fast Executable Suite",
        "",
        f"**{fast['status'].get('pass', 0)} passing of {fast['runnable']} runnable tests; "
        f"{fast['total']} total classified tests.**",
        "",
        "### Status",
        "",
        *markdown_table(fast["status"]),
        "",
        "### Module Families",
        "",
        *markdown_table(fast["family"]),
        "",
        "### Capability Profiles",
        "",
        *markdown_table(fast["profile"]),
        "",
        "## Full Deno-Vendored Corpus Inventory",
        "",
        f"**{corpus['total']} JavaScript tests inventoried.** These are coverage",
        "candidates, not executable compatibility claims for the Node 22 target.",
        "",
        "### Module Families",
        "",
        *markdown_table(corpus["family"]),
        "",
        "### Capability Profiles",
        "",
        *markdown_table(corpus["profile"]),
        "",
        "A compatibility percentage is valid only when its Node version, selected",
        "test denominator, and capability profile are stated together.",
        "",
    ]
    return "\n".join(lines)


def write_or_check(path, content, check):
    if check:
        if not path.exists() or path.read_text() != content:
            print(f"report drift: regenerate {path}", file=sys.stderr)
            return False
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f"wrote {path}")
    return True


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--expectations", type=pathlib.Path, default=DEFAULT_EXPECTATIONS)
    parser.add_argument("--inventory", type=pathlib.Path, default=DEFAULT_INVENTORY)
    parser.add_argument("--versions", type=pathlib.Path, default=DEFAULT_VERSIONS)
    parser.add_argument("--json-output", type=pathlib.Path, default=DEFAULT_JSON)
    parser.add_argument("--markdown-output", type=pathlib.Path, default=DEFAULT_MARKDOWN)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    expectations = json.loads(args.expectations.read_text())
    inventory = json.loads(args.inventory.read_text())
    versions = load_versions(args.versions)
    report = build_report(expectations, inventory, versions)
    json_content = json.dumps(report, indent=2) + "\n"
    markdown_content = render_markdown(report)
    ok = write_or_check(args.json_output, json_content, args.check)
    ok = write_or_check(args.markdown_output, markdown_content, args.check) and ok
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
