-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [mcpjs_verify]: function definitions
import Aeneas
import McpjsVerify.Types
import McpjsVerify.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace mcpjs_verify

/-- [mcpjs_verify::model::bytes_eq]: loop body 0:
    Source: 'src/model.rs', lines 18:4-25:1 -/
@[rust_loop_body]
def model.bytes_eq_loop.body
  (a : Slice Std.U8) (b : Slice Std.U8) (i : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i1 := Slice.len a
  if i < i1
  then
    let i2 ← Slice.index_usize a i
    let i3 ← Slice.index_usize b i
    if i2 != i3
    then ok (done false)
    else let i4 ← i + 1#usize
         ok (cont i4)
  else ok (done true)

/-- [mcpjs_verify::model::bytes_eq]: loop 0:
    Source: 'src/model.rs', lines 18:4-25:1 -/
@[rust_loop]
def model.bytes_eq_loop
  (a : Slice Std.U8) (b : Slice Std.U8) (i : Std.Usize) : Result Bool := do
  loop
    (fun i1 => model.bytes_eq_loop.body a b i1)
    i

/-- [mcpjs_verify::model::bytes_eq]:
    Source: 'src/model.rs', lines 13:0-25:1 -/
def model.bytes_eq (a : Slice Std.U8) (b : Slice Std.U8) : Result Bool := do
  let i := Slice.len a
  let i1 := Slice.len b
  if i != i1
  then ok false
  else model.bytes_eq_loop a b 0#usize

/-- [mcpjs_verify::model::ends_with]: loop body 0:
    Source: 'src/model.rs', lines 33:4-40:1 -/
@[rust_loop_body]
def model.ends_with_loop.body
  (haystack : Slice Std.U8) (suffix : Slice Std.U8) (start : Std.Usize)
  (i : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i1 := Slice.len suffix
  if i < i1
  then
    let i2 ← start + i
    let i3 ← Slice.index_usize haystack i2
    let i4 ← Slice.index_usize suffix i
    if i3 != i4
    then ok (done false)
    else let i5 ← i + 1#usize
         ok (cont i5)
  else ok (done true)

/-- [mcpjs_verify::model::ends_with]: loop 0:
    Source: 'src/model.rs', lines 33:4-40:1 -/
@[rust_loop]
def model.ends_with_loop
  (haystack : Slice Std.U8) (suffix : Slice Std.U8) (start : Std.Usize)
  (i : Std.Usize) :
  Result Bool
  := do
  loop
    (fun i1 => model.ends_with_loop.body haystack suffix start i1)
    i

/-- [mcpjs_verify::model::ends_with]:
    Source: 'src/model.rs', lines 27:0-40:1 -/
def model.ends_with
  (haystack : Slice Std.U8) (suffix : Slice Std.U8) : Result Bool := do
  let i := Slice.len suffix
  let i1 := Slice.len haystack
  if i > i1
  then ok false
  else
    let i2 := Slice.len haystack
    let i3 := Slice.len suffix
    let start ← i2 - i3
    model.ends_with_loop haystack suffix start 0#usize

/-- [mcpjs_verify::model::to_ascii_lowercase]: loop body 0:
    Source: 'src/model.rs', lines 45:4-53:5 -/
@[rust_loop_body]
def model.to_ascii_lowercase_loop.body
  (s : Slice Std.U8) (out : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  let i1 := Slice.len s
  if i < i1
  then
    let c ← Slice.index_usize s i
    let out1 ←
      if 65#u8 <= c
      then
        if c <= 90#u8
        then do
             let i2 ← c + 32#u8
             alloc.vec.Vec.push out i2
        else alloc.vec.Vec.push out c
      else alloc.vec.Vec.push out c
    let i2 ← i + 1#usize
    ok (cont (out1, i2))
  else ok (done out)

/-- [mcpjs_verify::model::to_ascii_lowercase]: loop 0:
    Source: 'src/model.rs', lines 45:4-53:5 -/
@[rust_loop]
def model.to_ascii_lowercase_loop
  (s : Slice Std.U8) (out : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (out1, i1) => model.to_ascii_lowercase_loop.body s out1 i1)
    (out, i)

/-- [mcpjs_verify::model::to_ascii_lowercase]:
    Source: 'src/model.rs', lines 42:0-55:1 -/
@[reducible]
def model.to_ascii_lowercase
  (s : Slice Std.U8) : Result (alloc.vec.Vec Std.U8) := do
  model.to_ascii_lowercase_loop s (alloc.vec.Vec.new Std.U8) 0#usize

/-- [mcpjs_verify::model::host_matches]:
    Source: 'src/model.rs', lines 71:0-81:1
    Visibility: public -/
def model.host_matches
  (pattern_raw : Slice Std.U8) (request_host : Slice Std.U8) :
  Result Bool
  := do
  let pattern ← model.to_ascii_lowercase pattern_raw
  let host ← model.to_ascii_lowercase request_host
  let b ← alloc.vec.Vec.is_empty Global pattern
  if b
  then
    let s := alloc.vec.Vec.deref host
    let s1 := alloc.vec.Vec.deref pattern
    model.bytes_eq s s1
  else
    let i ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U8)
        pattern 0#usize
    if i = 42#u8
    then
      let suffix ←
        alloc.vec.Vec.index (core.slice.index.SliceIndexRangeFromUsizeSlice
          Std.U8) pattern { start := 1#usize }
      let bare ←
        alloc.vec.Vec.index (core.slice.index.SliceIndexRangeFromUsizeSlice
          Std.U8) pattern { start := 2#usize }
      let s := alloc.vec.Vec.deref host
      let b1 ← model.bytes_eq s bare
      if b1
      then ok true
      else let s1 := alloc.vec.Vec.deref host
           model.ends_with s1 suffix
    else
      let s := alloc.vec.Vec.deref host
      let s1 := alloc.vec.Vec.deref pattern
      model.bytes_eq s s1

/-- [mcpjs_verify::model::is_ascii_whitespace]:
    Source: 'src/model.rs', lines 83:0-85:1 -/
def model.is_ascii_whitespace (c : Std.U8) : Result Bool := do
  if c = 32#u8
  then ok true
  else
    if c = 9#u8
    then ok true
    else
      if c = 10#u8
      then ok true
      else if c = 13#u8
           then ok true
           else ok (c = 12#u8)

/-- [mcpjs_verify::model::trim]: loop body 0:
    Source: 'src/model.rs', lines 89:4-91:5 -/
@[rust_loop_body]
def model.trim_loop0.body
  (s : Slice Std.U8) (start : Std.Usize) :
  Result (ControlFlow Std.Usize Std.Usize)
  := do
  let i := Slice.len s
  if start < i
  then
    let i1 ← Slice.index_usize s start
    let b ← model.is_ascii_whitespace i1
    if b
    then let start1 ← start + 1#usize
         ok (cont start1)
    else ok (done start)
  else ok (done start)

/-- [mcpjs_verify::model::trim]: loop 0:
    Source: 'src/model.rs', lines 89:4-91:5 -/
@[rust_loop]
def model.trim_loop0
  (s : Slice Std.U8) (start : Std.Usize) : Result Std.Usize := do
  loop
    (fun start1 => model.trim_loop0.body s start1)
    start

/-- [mcpjs_verify::model::trim]: loop body 1:
    Source: 'src/model.rs', lines 93:4-95:5 -/
@[rust_loop_body]
def model.trim_loop1.body
  (s : Slice Std.U8) (start : Std.Usize) (end1 : Std.Usize) :
  Result (ControlFlow Std.Usize Std.Usize)
  := do
  if end1 > start
  then
    let i ← end1 - 1#usize
    let i1 ← Slice.index_usize s i
    let b ← model.is_ascii_whitespace i1
    if b
    then ok (cont i)
    else ok (done end1)
  else ok (done end1)

/-- [mcpjs_verify::model::trim]: loop 1:
    Source: 'src/model.rs', lines 93:4-95:5 -/
@[rust_loop]
def model.trim_loop1
  (s : Slice Std.U8) (start : Std.Usize) (end1 : Std.Usize) :
  Result Std.Usize
  := do
  loop
    (fun end2 => model.trim_loop1.body s start end2)
    end1

/-- [mcpjs_verify::model::trim]:
    Source: 'src/model.rs', lines 87:0-97:1 -/
def model.trim (s : Slice Std.U8) : Result (Slice Std.U8) := do
  let start ← model.trim_loop0 s 0#usize
  let end1 := Slice.len s
  let end2 ← model.trim_loop1 s start end1
  core.slice.index.Slice.index (core.slice.index.SliceIndexRangeUsizeSlice
    Std.U8) s { start, «end» := end2 }

/-- [mcpjs_verify::model::parse_usize]: loop body 0:
    Source: 'src/model.rs', lines 107:4-124:1 -/
@[rust_loop_body]
def model.parse_usize_loop.body
  (s : Slice Std.U8) (acc : Std.Usize) (i : Std.Usize) :
  Result (ControlFlow (Std.Usize × Std.Usize) (Option Std.Usize))
  := do
  let i1 := Slice.len s
  if i < i1
  then
    let c ← Slice.index_usize s i
    if c < 48#u8
    then ok (done none)
    else
      if c > 57#u8
      then ok (done none)
      else
        let i2 ← c - 48#u8
        let d ← lift (UScalar.cast .Usize i2)
        let o ← lift (Usize.checked_mul acc 10#usize)
        match o with
        | none => ok (done none)
        | some v =>
          let o1 ← lift (Usize.checked_add v d)
          match o1 with
          | none => ok (done none)
          | some v1 => let i3 ← i + 1#usize
                       ok (cont (v1, i3))
  else ok (done (some acc))

/-- [mcpjs_verify::model::parse_usize]: loop 0:
    Source: 'src/model.rs', lines 107:4-124:1 -/
@[rust_loop]
def model.parse_usize_loop
  (s : Slice Std.U8) (acc : Std.Usize) (i : Std.Usize) :
  Result (Option Std.Usize)
  := do
  loop
    (fun (acc1, i1) => model.parse_usize_loop.body s acc1 i1)
    (acc, i)

/-- [mcpjs_verify::model::parse_usize]:
    Source: 'src/model.rs', lines 101:0-124:1 -/
def model.parse_usize (s : Slice Std.U8) : Result (Option Std.Usize) := do
  let b ← core.slice.Slice.is_empty s
  if b
  then ok none
  else model.parse_usize_loop s 0#usize 0#usize

/-- [mcpjs_verify::model::parse_memory_size]:
    Source: 'src/model.rs', lines 127:0-147:1
    Visibility: public -/
def model.parse_memory_size
  (s : Slice Std.U8) : Result (Option Std.Usize) := do
  let s1 ← model.trim s
  let b ← core.slice.Slice.is_empty s1
  if b
  then ok none
  else
    let i := Slice.len s1
    let i1 ← i - 1#usize
    let last ← Slice.index_usize s1 i1
    let (num_end, multiplier) ←
      if last = 107#u8
      then
        do
        let i2 := Slice.len s1
        let i3 ← i2 - 1#usize
        ok (i3, 1024#usize)
      else
        if last = 75#u8
        then
          do
          let i2 := Slice.len s1
          let i3 ← i2 - 1#usize
          ok (i3, 1024#usize)
        else
          if last = 109#u8
          then
            do
            let i2 := Slice.len s1
            let i3 ← i2 - 1#usize
            let i4 ← 1024#usize * 1024#usize
            ok (i3, i4)
          else
            if last = 77#u8
            then
              do
              let i2 := Slice.len s1
              let i3 ← i2 - 1#usize
              let i4 ← 1024#usize * 1024#usize
              ok (i3, i4)
            else
              if last = 103#u8
              then
                do
                let i2 := Slice.len s1
                let i3 ← i2 - 1#usize
                let i4 ← 1024#usize * 1024#usize
                let i5 ← i4 * 1024#usize
                ok (i3, i5)
              else
                if last = 71#u8
                then
                  do
                  let i2 := Slice.len s1
                  let i3 ← i2 - 1#usize
                  let i4 ← 1024#usize * 1024#usize
                  let i5 ← i4 * 1024#usize
                  ok (i3, i5)
                else let i2 := Slice.len s1
                     ok (i2, 1#usize)
    let s2 ←
      core.slice.index.Slice.index (core.slice.index.SliceIndexRangeUsizeSlice
        Std.U8) s1 { start := 0#usize, «end» := num_end }
    let o ← model.parse_usize s2
    match o with
    | none => ok none
    | some n => ok (Usize.checked_mul n multiplier)

/-- [mcpjs_verify::model::is_ascii_alphabetic]:
    Source: 'src/model.rs', lines 149:0-151:1 -/
def model.is_ascii_alphabetic (c : Std.U8) : Result Bool := do
  if 97#u8 <= c
  then
    if c <= 122#u8
    then ok true
    else if 65#u8 <= c
         then ok (c <= 90#u8)
         else ok false
  else if 65#u8 <= c
       then ok (c <= 90#u8)
       else ok false

/-- [mcpjs_verify::model::is_ascii_alphanumeric]:
    Source: 'src/model.rs', lines 153:0-155:1 -/
def model.is_ascii_alphanumeric (c : Std.U8) : Result Bool := do
  let b ← model.is_ascii_alphabetic c
  if b
  then ok true
  else if 48#u8 <= c
       then ok (c <= 57#u8)
       else ok false

/-- [mcpjs_verify::model::validate_wasm_name]: loop body 0:
    Source: 'src/model.rs', lines 168:4-176:1
    Visibility: public -/
@[rust_loop_body]
def model.validate_wasm_name_loop0.body
  (name1 : Slice Std.U8) (i : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i1 := Slice.len name1
  if i < i1
  then
    let c ← Slice.index_usize name1 i
    let b ← model.is_ascii_alphanumeric c
    if b
    then let i2 ← i + 1#usize
         ok (cont i2)
    else
      if c != 95#u8
      then
        if c != 36#u8
        then ok (done false)
        else let i2 ← i + 1#usize
             ok (cont i2)
      else let i2 ← i + 1#usize
           ok (cont i2)
  else ok (done true)

/-- [mcpjs_verify::model::validate_wasm_name]: loop 0:
    Source: 'src/model.rs', lines 168:4-176:1
    Visibility: public -/
@[rust_loop]
def model.validate_wasm_name_loop0
  (name1 : Slice Std.U8) (i : Std.Usize) : Result Bool := do
  loop
    (fun i1 => model.validate_wasm_name_loop0.body name1 i1)
    i

/-- [mcpjs_verify::model::validate_wasm_name]: loop body 1:
    Source: 'src/model.rs', lines 168:4-176:1
    Visibility: public -/
@[rust_loop_body]
def model.validate_wasm_name_loop1.body
  (name1 : Slice Std.U8) (i : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i1 := Slice.len name1
  if i < i1
  then
    let c ← Slice.index_usize name1 i
    let b ← model.is_ascii_alphanumeric c
    if b
    then let i2 ← i + 1#usize
         ok (cont i2)
    else
      if c != 95#u8
      then
        if c != 36#u8
        then ok (done false)
        else let i2 ← i + 1#usize
             ok (cont i2)
      else let i2 ← i + 1#usize
           ok (cont i2)
  else ok (done true)

/-- [mcpjs_verify::model::validate_wasm_name]: loop 1:
    Source: 'src/model.rs', lines 168:4-176:1
    Visibility: public -/
@[rust_loop]
def model.validate_wasm_name_loop1
  (name1 : Slice Std.U8) (i : Std.Usize) : Result Bool := do
  loop
    (fun i1 => model.validate_wasm_name_loop1.body name1 i1)
    i

/-- [mcpjs_verify::model::validate_wasm_name]: loop body 2:
    Source: 'src/model.rs', lines 168:4-176:1
    Visibility: public -/
@[rust_loop_body]
def model.validate_wasm_name_loop2.body
  (name1 : Slice Std.U8) (i : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i1 := Slice.len name1
  if i < i1
  then
    let c ← Slice.index_usize name1 i
    let b ← model.is_ascii_alphanumeric c
    if b
    then let i2 ← i + 1#usize
         ok (cont i2)
    else
      if c != 95#u8
      then
        if c != 36#u8
        then ok (done false)
        else let i2 ← i + 1#usize
             ok (cont i2)
      else let i2 ← i + 1#usize
           ok (cont i2)
  else ok (done true)

/-- [mcpjs_verify::model::validate_wasm_name]: loop 2:
    Source: 'src/model.rs', lines 168:4-176:1
    Visibility: public -/
@[rust_loop]
def model.validate_wasm_name_loop2
  (name1 : Slice Std.U8) (i : Std.Usize) : Result Bool := do
  loop
    (fun i1 => model.validate_wasm_name_loop2.body name1 i1)
    i

/-- [mcpjs_verify::model::validate_wasm_name]:
    Source: 'src/model.rs', lines 159:0-176:1
    Visibility: public -/
def model.validate_wasm_name (name1 : Slice Std.U8) : Result Bool := do
  let b ← core.slice.Slice.is_empty name1
  if b
  then ok false
  else
    let first ← Slice.index_usize name1 0#usize
    let b1 ← model.is_ascii_alphabetic first
    if b1
    then model.validate_wasm_name_loop0 name1 1#usize
    else
      if first != 95#u8
      then
        if first != 36#u8
        then ok false
        else model.validate_wasm_name_loop1 name1 1#usize
      else model.validate_wasm_name_loop2 name1 1#usize

end mcpjs_verify
