name: Release Rust Server

on:
  push:
    tags:
      - 'v*.*.*'   # Triggers on version tags like v1.2.3

  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

    # install nix with determinat nix installer 
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Run `nix build`
        run: cd server && nix develop --command cargo build --release

      - name: Prepare binary for release
        run: |
          mkdir -p dist
          cp server/target/release/server dist/mcp-v8
        # Replace <your-binary-name> with the actual binary name

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/mcp-v8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}