name: Release Rust Server

on:
  push:
    tags:
      - 'v*.*.*'   # Triggers on version tags like v1.2.3

  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

    # install nix with determinat nix installer 
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: "server"
    #   - install targets 
      - name: Install targets
        run: |
          nix develop --command rustup target add x86_64-apple-darwin
          nix develop --command rustup target add aarch64-apple-darwin
          nix develop --command rustup target add x86_64-unknown-linux-gnu
          nix develop --command rustup target add aarch64-unknown-linux-gnu

      - name: Build macOS binary
        run: cd server && nix develop --command cargo zigbuild --release --target x86_64-apple-darwin

    # arm macos
      - name: Build arm macos binary
        run: cd server && nix develop --command cargo zigbuild --release --target aarch64-apple-darwin
  
      - name: Build Linux binary
        run: cd server && nix develop --command cargo build --release --target x86_64-unknown-linux-gnu

      # arm linux
      - name: Build arm linux binary
        run: cd server && nix develop --command cargo build --release --target aarch64-unknown-linux-gnu

      - name: Prepare binaries for release
        run: |
          mkdir -p dist
          cp server/target/x86_64-unknown-linux-gnu/release/server dist/mcp-v8-linux
          cp server/target/x86_64-apple-darwin/release/server dist/mcp-v8-macos

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/mcp-v8-linux
            dist/mcp-v8-macos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}